server.address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projeto_final
    username: postgres
    password: aluno123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate:
      format_sql: true
      jdbc.lob.non_contextual_creation: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet.multipart:
   max-file-size: 2MB
   max-request-size: 2MB

logging:
  level:
    org:
      hibernate:
        type: trace

