server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/projeto_final
    username: postgres
    password: aluno123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace

